### ISSUE TITLE
Fails to find standard.js with lerna

### ISSUE THREAD

**Issue by ReadyPlayerNaN** [TheBrainFamily/jest-runner-standard#3]
Hi, thanks for this runner, I've been using it for quite some time now. I've come to a troublesome interaction with lerna and react-scripts configuration.

In lerna, the file structure should look like this:

```
lerna-root/
├ node_modules/
├ packages/
│ └ project-root/
│   ├ (project files)
│   └ (no node modules)
```

Unfortunately, react-scripts define webpack loaders to cache stuff under project's node_modules. Like this:

```
lerna-root/
├ node_modules/
├ packages/
│ └ project-root/
│    ├ node_modules/
│    │  └ .cache/
│    │      ├ babel-loader/
│    │      └ eslint-loader/
│    └ (project files)
```

Well, jest-runner-standard is configured to find the closest node_modules and use them as a source to find standard, ignoring the lerna-root node_modules. The result is:

```
Test suite failed to run

    Cannot find module '.../packages/improv-match-referee/node_modules/standard'
    Require stack:
    - .../node_modules/jest-runner-standard/helpers/getLocalStandard.js
    - .../node_modules/jest-runner-standard/run.js
    - .../node_modules/jest-worker/build/workers/processChild.js

      at exports.getLocalStandard (../../node_modules/jest-runner-standard/helpers/getLocalStandard.js:6:10)
      at Function.module.exports (../../node_modules/jest-runner-standard/run.js:11:20)
```

I propose that the `getLocalStandard` gets extended so it looks for standard in project root ancestor directories as well.

**Comment by lgandecki** [comment]
makes sense, want to give it a try?

**Comment by ReadyPlayerNaN** [comment]
> makes sense, want to give it a try?

ok, I will.

**Comment by ReadyPlayerNaN** [comment]
@lgandecki the PR is there, please check it out :-)

**Comment by lgandecki** [comment]
Thank you so much! :-) And sorry! 
Super busy, I want to try it out with and without lerna before releasing. Meanwhile are you able to use it without the release?

**Comment by ReadyPlayerNaN** [comment]
Yes, I installed a local copy of the runner as if it was a normal npm package and it worked for me. The change is very small and I developed it test driven, so I don't expect any problems.

**Comment by ReadyPlayerNaN** [comment]
Another month has passed, @lgandecki :-)

**Comment by lgandecki** [comment]
you guilt tripped me here! :) It was just one month, not "another" :) . Anyway, I tested it and released, it's at 0.1.0. Sorry for the delay - you are probably the only person using that feature and since you were able to use it without the release it didn't seem like the highest priority.. I have 100k weekly installs of cypress-cucumber-preprocessor and a ton of issues to deal with there.. ;) anyway, enjoy! Glad this is useful :) I personally switched to eslint..

**Comment by ReadyPlayerNaN** [comment]
Thanks for merging and sorry about the guilt tripping :-D Yeah, eslint is fine, but I don't wanna care about configuring it, so standard ftw. However, if it was possible to run standard with jest-runner-eslint, I'd prefer that.

**Comment by lgandecki** [comment]
You are right, it's a great idea to have a standard setup and no configuration :) That's why we loved it initially at TheBrain. It worked great for putting an end to styling wars by enforcing a set of styles.
Since then though, Prettier is doing much better job with that, and we do use eslint for many other things now, and standard is limiting what we can do (I wouldn't necessarily want to modify standard rules, but I'd like to extend them)

**Comment by ReadyPlayerNaN** [comment]
> Prettier is doing much better job

Have you seen [prettier-standard](https://www.npmjs.com/package/prettier-standard)? :-D It can even be used in vim via Ale.

> standard is limiting what we can do (I wouldn't necessarily want to modify standard rules, but I'd like to extend them)

It's just js coding style, what more do you need?
